from collections.abc import AsyncIterator, Awaitable
from typing import Any, Protocol, TypeVar


class AnyPaginator(Protocol):
    def paginate(self, **kwargs: object) -> "AnyAsyncIterator": ...


class AnyAsyncIterator(Protocol):
    def __aiter__(self) -> "AnyAsyncIterator": ...
    async def __anext__(self) -> dict[str, Any]: ...


class S3Client(Protocol):
    @property
    def exceptions(self) -> Any: ...

    async def get_object(self, Bucket: str, Key: str, **kwargs: object) -> dict[str, object]: ...
    async def head_object(self, Bucket: str, Key: str, **kwargs: object) -> dict[str, object]: ...
    async def put_object(
        self, Bucket: str, Key: str, Body: object, **kwargs: object
    ) -> dict[str, object]: ...
    async def delete_object(self, Bucket: str, Key: str, **kwargs: object) -> dict[str, object]: ...
    async def list_objects_v2(
        self, Bucket: str, Prefix: str = "", **kwargs: object
    ) -> dict[str, object]: ...
    async def copy_object(
        self,
        Bucket: str,
        CopySource: dict[str, str],
        Key: str,
        MetadataDirective: str | None = None,
        ContentType: str | None = None,
        **kwargs: object,
    ) -> dict[str, object]: ...
    async def upload_file(self, Filename: str, Bucket: str, Key: str, **kwargs: object) -> None: ...
    async def upload_fileobj(
        self, Fileobj: object, Bucket: str, Key: str, **kwargs: object
    ) -> None: ...
    async def download_fileobj(
        self, Bucket: str, Key: str, Fileobj: object, **kwargs: object
    ) -> None: ...
    async def generate_presigned_url(
        self,
        ClientMethod: str,
        Params: dict[str, object] | None = None,
        ExpiresIn: int = 3600,
        HttpMethod: str | None = None,
    ) -> str: ...
    async def create_multipart_upload(
        self, Bucket: str, Key: str, **kwargs: object
    ) -> dict[str, object]: ...
    async def upload_part(
        self, Bucket: str, Key: str, PartNumber: int, UploadId: str, Body: object, **kwargs: object
    ) -> dict[str, object]: ...
    async def complete_multipart_upload(
        self,
        Bucket: str,
        Key: str,
        UploadId: str,
        MultipartUpload: dict[str, object],
        **kwargs: object,
    ) -> dict[str, object]: ...
    async def abort_multipart_upload(
        self, Bucket: str, Key: str, UploadId: str, **kwargs: object
    ) -> dict[str, object]: ...
    def get_paginator(self, operation_name: str) -> "AnyPaginator": ...
    async def __aenter__(self) -> "S3Client": ...
    async def __aexit__(self, exc_type: object, exc_val: object, exc_tb: object) -> None: ...
    async def close(self) -> None: ...


T = TypeVar("T")


class RedisProtocol(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def set(
        self, key: str, value: str, ex: int | None = None, nx: bool = False
    ) -> bool | None: ...
    async def hset(
        self,
        name: str,
        key: str | None = None,
        value: str | None = None,
        mapping: dict[str, str] | None = None,
    ) -> int: ...
    async def hgetall(self, name: str) -> dict[bytes, bytes]: ...
    async def expire(self, name: str, time: int) -> bool: ...
    async def incr(self, name: str, amount: int = 1) -> int: ...
    async def decr(self, name: str, amount: int = 1) -> int: ...
    async def delete(self, *names: str) -> int: ...
    async def sadd(self, name: str, *values: str) -> int: ...
    async def srem(self, name: str, *values: str) -> int: ...
    async def lrange(self, name: str, start: int, end: int) -> list[str]: ...
    async def llen(self, name: str) -> int: ...
    async def zadd(self, name: str, mapping: dict[str, float]) -> int: ...
    async def zrem(self, name: str, *values: str) -> int: ...
    async def zcard(self, name: str) -> int: ...
    async def zremrangebyscore(self, name: str, min: str | float, max: str | float) -> int: ...
    def execute_command(self, *args: str | int | float) -> Awaitable[str | bytes | int | None]: ...
    def pubsub(self) -> "PubSubProtocol": ...


class PubSubProtocol(Protocol):
    async def subscribe(self, *channels: str) -> None: ...
    async def unsubscribe(self, *channels: str) -> None: ...
    async def reset(self) -> None: ...
    def listen(self) -> AsyncIterator[dict[str, str | bytes]]: ...
