"""Structured error code constants for the upload pipeline.

Every BadRequestError / ServiceUnavailableError raised by upload-related code
should include one of these codes as the ``code`` parameter. Frontend consumers
can match on the code for precise error handling without parsing the human-readable
``detail`` string.
"""

# File validation errors
ERR_FILE_TOO_LARGE = "ERR_FILE_TOO_LARGE"
ERR_FILENAME_TOO_LONG = "ERR_FILENAME_TOO_LONG"
ERR_TYPE_NOT_ALLOWED = "ERR_TYPE_NOT_ALLOWED"
ERR_MIME_MISMATCH = "ERR_MIME_MISMATCH"

# SVG-specific
ERR_SVG_MALFORMED = "ERR_SVG_MALFORMED"
ERR_SVG_UNSAFE = "ERR_SVG_UNSAFE"

# Scanning
ERR_MALWARE_DETECTED = "ERR_MALWARE_DETECTED"
ERR_SCAN_UNAVAILABLE = "ERR_SCAN_UNAVAILABLE"

# Quota / rate limiting
ERR_QUOTA_EXCEEDED = "ERR_QUOTA_EXCEEDED"

# Intent / idempotency
ERR_INTENT_EXPIRED = "ERR_INTENT_EXPIRED"
ERR_INTENT_MISMATCH = "ERR_INTENT_MISMATCH"

# Deduplication (CAS hit — not an error per se, but signals a skip)
ERR_DUPLICATE = "ERR_DUPLICATE"

# Generic processing failure
ERR_PROCESSING_FAILED = "ERR_PROCESSING_FAILED"

# tus-specific
ERR_TUS_INVALID_OFFSET = "ERR_TUS_INVALID_OFFSET"
ERR_TUS_UPLOAD_NOT_FOUND = "ERR_TUS_UPLOAD_NOT_FOUND"
ERR_TUS_CONTENT_TYPE = "ERR_TUS_CONTENT_TYPE"
ERR_TUS_CHUNK_TOO_SMALL = "ERR_TUS_CHUNK_TOO_SMALL"
ERR_TUS_CHUNK_TOO_LARGE = "ERR_TUS_CHUNK_TOO_LARGE"
ERR_TUS_CHECKSUM_MISMATCH = "ERR_TUS_CHECKSUM_MISMATCH"
ERR_TUS_CONCURRENCY_LIMIT = "ERR_TUS_CONCURRENCY_LIMIT"
ERR_STORAGE_FULL = "ERR_STORAGE_FULL"

# Batch-zip errors
ERR_INVALID_ZIP = "ERR_INVALID_ZIP"
ERR_ZIP_BOMB = "ERR_ZIP_BOMB"
ERR_BATCH_TOO_LARGE = "ERR_BATCH_TOO_LARGE"
