"""add allow_all_domains to auth_configs

Revision ID: 037cdf394b1d
Revises: c8a33c7d333a
Create Date: 2026-04-17 13:14:00.186200

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '037cdf394b1d'
down_revision: str | None = 'c8a33c7d333a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_configs', sa.Column('allow_all_domains', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_configs', 'allow_all_domains')
    # ### end Alembic commands ###
