"""Add auto_approve to User

Revision ID: 0848234829d9
Revises: d1e2f3a4b5c6
Create Date: 2026-04-10 09:32:16.583322

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0848234829d9'
down_revision: str | None = 'd1e2f3a4b5c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auto_approve', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auto_approve')
    # ### end Alembic commands ###
