"""add jwt expiry to auth_configs

Revision ID: 12f8d80994aa
Revises: 7d4f14e8af8c
Create Date: 2026-04-17 13:43:09.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '12f8d80994aa'
down_revision: str | None = '7d4f14e8af8c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_configs', sa.Column('jwt_access_expire_days', sa.Integer(), server_default='7', nullable=False))
    op.add_column('auth_configs', sa.Column('jwt_refresh_expire_days', sa.Integer(), server_default='31', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_configs', 'jwt_refresh_expire_days')
    op.drop_column('auth_configs', 'jwt_access_expire_days')
    # ### end Alembic commands ###
