"""add_file_config_fields

Revision ID: 15a907a42e43
Revises: d3105dd5a86d
Create Date: 2026-04-17 16:49:39.797222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '15a907a42e43'
down_revision: Union[str, None] = 'd3105dd5a86d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_configs', sa.Column('max_file_size_mb', sa.Integer(), nullable=True))
    op.add_column('auth_configs', sa.Column('max_image_size_mb', sa.Integer(), nullable=True))
    op.add_column('auth_configs', sa.Column('max_audio_size_mb', sa.Integer(), nullable=True))
    op.add_column('auth_configs', sa.Column('max_video_size_mb', sa.Integer(), nullable=True))
    op.add_column('auth_configs', sa.Column('max_document_size_mb', sa.Integer(), nullable=True))
    op.add_column('auth_configs', sa.Column('max_office_size_mb', sa.Integer(), nullable=True))
    op.add_column('auth_configs', sa.Column('max_text_size_mb', sa.Integer(), nullable=True))
    op.add_column('auth_configs', sa.Column('pdf_quality', sa.Integer(), nullable=True))
    op.add_column('auth_configs', sa.Column('video_compression_profile', sa.String(length=20), nullable=True))
    op.add_column('auth_configs', sa.Column('allowed_extensions', sa.Text(), nullable=True))
    op.add_column('auth_configs', sa.Column('allowed_mime_types', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_configs', 'allowed_mime_types')
    op.drop_column('auth_configs', 'allowed_extensions')
    op.drop_column('auth_configs', 'video_compression_profile')
    op.drop_column('auth_configs', 'pdf_quality')
    op.drop_column('auth_configs', 'max_text_size_mb')
    op.drop_column('auth_configs', 'max_office_size_mb')
    op.drop_column('auth_configs', 'max_document_size_mb')
    op.drop_column('auth_configs', 'max_video_size_mb')
    op.drop_column('auth_configs', 'max_audio_size_mb')
    op.drop_column('auth_configs', 'max_image_size_mb')
    op.drop_column('auth_configs', 'max_file_size_mb')
    # ### end Alembic commands ###
