"""add smtp settings to auth_configs

Revision ID: 7506c16e32dd
Revises: 12f8d80994aa
Create Date: 2026-04-17 13:48:42.592002

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7506c16e32dd'
down_revision: str | None = '12f8d80994aa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_configs', sa.Column('smtp_host', sa.String(length=255), nullable=True))
    op.add_column('auth_configs', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('auth_configs', sa.Column('smtp_user', sa.String(length=255), nullable=True))
    op.add_column('auth_configs', sa.Column('smtp_password', sa.String(length=255), nullable=True))
    op.add_column('auth_configs', sa.Column('smtp_from', sa.String(length=255), nullable=True))
    op.add_column('auth_configs', sa.Column('smtp_use_tls', sa.Boolean(), server_default='true', nullable=False))

    # Re-apply foreign key fixes that were incorrectly generated as drops
    op.drop_constraint('annotations_author_id_fkey', 'annotations', type_='foreignkey')
    op.create_foreign_key(None, 'annotations', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('comments_author_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('flags_reporter_id_fkey', 'flags', type_='foreignkey')
    op.create_foreign_key(None, 'flags', 'users', ['reporter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flags', type_='foreignkey')
    op.create_foreign_key('flags_reporter_id_fkey', 'flags', 'users', ['reporter_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_author_id_fkey', 'comments', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.drop_column('auth_configs', 'smtp_use_tls')
    op.drop_column('auth_configs', 'smtp_from')
    op.drop_column('auth_configs', 'smtp_password')
    op.drop_column('auth_configs', 'smtp_user')
    op.drop_column('auth_configs', 'smtp_port')
    op.drop_column('auth_configs', 'smtp_host')
    op.drop_constraint(None, 'annotations', type_='foreignkey')
    op.create_foreign_key('annotations_author_id_fkey', 'annotations', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('idx_tags_name'), 'tags', ['name'], unique=False)
    op.create_index(op.f('ix_pull_requests_reverts_pr_id'), 'pull_requests', ['reverts_pr_id'], unique=False, postgresql_where='(reverts_pr_id IS NOT NULL)')
    op.create_index(op.f('ix_pull_requests_payload_gin'), 'pull_requests', ['payload'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_pull_requests_status'), 'pull_requests', ['status'], unique=False)
    op.create_index(op.f('idx_pull_requests_author'), 'pull_requests', ['author_id'], unique=False)
    op.create_index(op.f('idx_pr_comments_pr'), 'pr_comments', ['pr_id'], unique=False)
    op.create_index(op.f('idx_pr_comments_parent'), 'pr_comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_materials_deleted_at'), 'materials', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NOT NULL)')
    op.create_index(op.f('idx_materials_type'), 'materials', ['type'], unique=False)
    op.create_index(op.f('idx_materials_slug'), 'materials', ['slug'], unique=False)
    op.create_index(op.f('idx_materials_parent_material'), 'materials', ['parent_material_id'], unique=False)
    op.create_index(op.f('idx_materials_directory'), 'materials', ['directory_id'], unique=False)
    op.create_index(op.f('idx_materials_author'), 'materials', ['author_id'], unique=False)
    op.create_index(op.f('ix_material_versions_deleted_at'), 'material_versions', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NOT NULL)')
    op.create_index(op.f('idx_material_versions_material'), 'material_versions', ['material_id'], unique=False)
    op.create_index(op.f('idx_material_versions_author'), 'material_versions', ['author_id'], unique=False)
    op.drop_constraint(None, 'flags', type_='foreignkey')
    op.create_foreign_key(op.f('flags_reporter_id_fkey'), 'flags', 'users', ['reporter_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_featured_items_window'), 'featured_items', ['start_at', 'end_at'], unique=False)
    op.create_index(op.f('ix_featured_items_priority'), 'featured_items', ['priority'], unique=False)
    op.create_index(op.f('ix_directories_deleted_at'), 'directories', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NOT NULL)')
    op.create_index(op.f('idx_directories_type'), 'directories', ['type'], unique=False)
    op.create_index(op.f('idx_directories_slug'), 'directories', ['slug'], unique=False)
    op.create_index(op.f('idx_directories_parent'), 'directories', ['parent_id'], unique=False)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_author_id_fkey'), 'comments', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.drop_column('auth_configs', 'smtp_use_tls')
    op.drop_column('auth_configs', 'smtp_from')
    op.drop_column('auth_configs', 'smtp_password')
    op.drop_column('auth_configs', 'smtp_user')
    op.drop_column('auth_configs', 'smtp_port')
    op.drop_column('auth_configs', 'smtp_host')
    op.drop_constraint(None, 'annotations', type_='foreignkey')
    op.create_foreign_key(op.f('annotations_author_id_fkey'), 'annotations', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_annotations_version'), 'annotations', ['version_id'], unique=False)
    op.create_index(op.f('idx_annotations_thread'), 'annotations', ['thread_id'], unique=False)
    op.create_index(op.f('idx_annotations_material'), 'annotations', ['material_id'], unique=False)
    op.create_index(op.f('idx_annotations_author'), 'annotations', ['author_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('upload_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quarantine_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('final_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('size_bytes', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('content_sha256', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('error_detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('webhook_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('pipeline_stage', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cas_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('cas_ref_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('thumbnail_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('uploads_pkey')),
    sa.UniqueConstraint('upload_id', name=op.f('uq_uploads_upload_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_uploads_user_status'), 'uploads', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_uploads_upload_id'), 'uploads', ['upload_id'], unique=True)
    op.create_index(op.f('ix_uploads_sha256'), 'uploads', ['sha256'], unique=False)
    op.create_index(op.f('ix_uploads_content_sha256'), 'uploads', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_uploads_cas_key'), 'uploads', ['cas_key'], unique=False)
    # ### end Alembic commands ###
