"""add smtp settings to auth_configs

Revision ID: 7506c16e32dd
Revises: 12f8d80994aa
Create Date: 2026-04-17 13:48:42.592002

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7506c16e32dd'
down_revision: str | None = '12f8d80994aa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_configs', sa.Column('smtp_host', sa.String(length=255), nullable=True))
    op.add_column('auth_configs', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('auth_configs', sa.Column('smtp_user', sa.String(length=255), nullable=True))
    op.add_column('auth_configs', sa.Column('smtp_password', sa.String(length=255), nullable=True))
    op.add_column('auth_configs', sa.Column('smtp_from', sa.String(length=255), nullable=True))
    op.add_column('auth_configs', sa.Column('smtp_use_tls', sa.Boolean(), server_default='true', nullable=False))

    # Re-apply foreign key fixes that were incorrectly generated as drops
    op.drop_constraint('annotations_author_id_fkey', 'annotations', type_='foreignkey')
    op.create_foreign_key(None, 'annotations', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('comments_author_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('flags_reporter_id_fkey', 'flags', type_='foreignkey')
    op.create_foreign_key(None, 'flags', 'users', ['reporter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_user_status'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_upload_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_sha256'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_content_sha256'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_cas_key'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('idx_users_deleted_at'), table_name='users')
    op.drop_index(op.f('idx_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_pull_requests_reverts_pr_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_payload_gin'), table_name='pull_requests')
    op.drop_index(op.f('idx_pull_requests_status'), table_name='pull_requests')
    op.drop_index(op.f('idx_pull_requests_author'), table_name='pull_requests')
    op.drop_index(op.f('idx_pr_comments_pr'), table_name='pr_comments')
    op.drop_index(op.f('idx_pr_comments_parent'), table_name='pr_comments')
    op.drop_index(op.f('ix_materials_deleted_at'), table_name='materials')
    op.drop_index(op.f('idx_materials_type'), table_name='materials')
    op.drop_index(op.f('idx_materials_slug'), table_name='materials')
    op.drop_index(op.f('idx_materials_parent_material'), table_name='materials')
    op.drop_index(op.f('idx_materials_directory'), table_name='materials')
    op.drop_index(op.f('idx_materials_author'), table_name='materials')
    op.drop_index(op.f('ix_material_versions_deleted_at'), table_name='material_versions')
    op.drop_index(op.f('idx_material_versions_material'), table_name='material_versions')
    op.drop_index(op.f('idx_material_versions_author'), table_name='material_versions')
    op.drop_index(op.f('ix_featured_items_window'), table_name='featured_items')
    op.drop_index(op.f('ix_featured_items_priority'), table_name='featured_items')
    op.drop_index(op.f('ix_directories_deleted_at'), table_name='directories')
    op.drop_index(op.f('idx_directories_type'), table_name='directories')
    op.drop_index(op.f('idx_directories_slug'), table_name='directories')
    op.drop_index(op.f('idx_directories_parent'), table_name='directories')
    op.drop_index(op.f('idx_annotations_version'), table_name='annotations')
    op.drop_index(op.f('idx_annotations_thread'), table_name='annotations')
    op.drop_index(op.f('idx_annotations_material'), table_name='annotations')
    op.drop_index(op.f('idx_annotations_author'), table_name='annotations')

    op.drop_constraint('annotations_author_id_fkey', 'annotations', type_='foreignkey')
    op.create_foreign_key('annotations_author_id_fkey', 'annotations', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('comments_author_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key('comments_author_id_fkey', 'comments', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('flags_reporter_id_fkey', 'flags', type_='foreignkey')
    op.create_foreign_key('flags_reporter_id_fkey', 'flags', 'users', ['reporter_id'], ['id'], ondelete='SET NULL')

    op.drop_column('auth_configs', 'smtp_use_tls')
    op.drop_column('auth_configs', 'smtp_from')
    op.drop_column('auth_configs', 'smtp_password')
    op.drop_column('auth_configs', 'smtp_user')
    op.drop_column('auth_configs', 'smtp_port')
    op.drop_column('auth_configs', 'smtp_host')
    # ### end Alembic commands ###
