"""remove open_registration from auth_configs

Revision ID: 7d4f14e8af8c
Revises: f185c9bb57ba
Create Date: 2026-04-17 13:35:05.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '7d4f14e8af8c'
down_revision: str | None = 'f185c9bb57ba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_configs', 'open_registration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_configs', sa.Column('open_registration', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###
