"""add google oauth client id

Revision ID: c8a33c7d333a
Revises: b2c3d4e5f6a7
Create Date: 2026-04-17 12:52:53.882746

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'c8a33c7d333a'
down_revision: str | None = 'b2c3d4e5f6a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_configs', sa.Column('google_client_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_configs', 'google_client_id')
    # ### end Alembic commands ###
