"""add s3 storage fields

Revision ID: d3105dd5a86d
Revises: 7506c16e32dd
Create Date: 2026-04-17 16:40:56.815194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd3105dd5a86d'
down_revision: Union[str, None] = '7506c16e32dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_configs', sa.Column('s3_endpoint', sa.String(length=255), nullable=True))
    op.add_column('auth_configs', sa.Column('s3_access_key', sa.String(length=255), nullable=True))
    op.add_column('auth_configs', sa.Column('s3_secret_key', sa.String(length=255), nullable=True))
    op.add_column('auth_configs', sa.Column('s3_bucket', sa.String(length=100), nullable=True))
    op.add_column('auth_configs', sa.Column('s3_public_endpoint', sa.String(length=255), nullable=True))
    op.add_column('auth_configs', sa.Column('s3_region', sa.String(length=50), nullable=True))
    op.add_column('auth_configs', sa.Column('s3_use_ssl', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_configs', 's3_use_ssl')
    op.drop_column('auth_configs', 's3_region')
    op.drop_column('auth_configs', 's3_public_endpoint')
    op.drop_column('auth_configs', 's3_bucket')
    op.drop_column('auth_configs', 's3_secret_key')
    op.drop_column('auth_configs', 's3_access_key')
    op.drop_column('auth_configs', 's3_endpoint')
    # ### end Alembic commands ###
