"""add classic_auth_enabled to auth_configs

Revision ID: f185c9bb57ba
Revises: 037cdf394b1d
Create Date: 2026-04-17 13:30:31.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f185c9bb57ba'
down_revision: str | None = '037cdf394b1d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_configs', sa.Column('classic_auth_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_configs', 'classic_auth_enabled')
    # ### end Alembic commands ###
